source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.0'
gem 'json', '~> 2.15'
gem 'rackup', '~> 2.0'
gem 'onnxruntime', '~> 0.10'
gem 'tokenizers', '~> 0.6'
gem 'numo-narray', '~> 0.9'

# Async/Falcon support
gem 'falcon', '~> 0.47'
gem 'async', '~> 2.0'
gem 'async-http', '~> 0.66'
